Liveness tests, worker point to node's IP and fix haproxy cfg build bug
This commit adds liveness tests for the coredns,mdns-publisher,
haproxy and keepalived static pods, changes worker node
/etc/resolv.conf to point to node's IP instead of 127.0.0.1 and
fix the bug generating haproxy cfg file

diff --git a/templates/worker/00-worker/baremetal/files/NetworkManager-dns-vip-prepender-worker.yaml b/templates/worker/00-worker/baremetal/files/NetworkManager-dns-vip-prepender-worker.yaml
--- a/templates/worker/00-worker/baremetal/files/NetworkManager-dns-vip-prepender-worker.yaml
+++ b/templates/worker/00-worker/baremetal/files/NetworkManager-dns-vip-prepender-worker.yaml
@@ -12,21 +12,28 @@ contents:
         pre-up)
         logger -s "NM dns-vip-prepender-worker triggered by pre-upping ${1}."
         CLUSTER_DOMAIN="$(/usr/local/bin/clusterinfo DOMAIN)"
-        API_VIP="127.0.0.1"
+        if ! HOST_QUERY="$(host ns1.${CLUSTER_DOMAIN})" ; then
+            logger -s "NM dns-vip-prepender: nameserver could not be resolved, exiting"
+            exit 0
+        fi
+        DNS_VIP=$(echo "${HOST_QUERY}" | awk '{print $NF}')
+        IFACE_CIDRS="$(ip addr show | grep -v "scope host" | grep -Po 'inet \K[\d.]+/[\d.]+' | xargs)"
+        SUBNET_CIDR="$(/usr/local/bin/get_vip_subnet_cidr "$DNS_VIP" "$IFACE_CIDRS")"
+        WORKER_BM_IP="$(ip -o addr show to "$SUBNET_CIDR" | awk '{print $4}' | awk -F/ '{print $1}')"
         set +e
-        if [[ -n $API_VIP ]]; then
-            logger -s "NM dns-vip-prepender-worker: Checking if API VIP is the first entry in resolv.conf"
-            if grep nameserver /etc/resolv.conf | head -n 1 | grep -q "$API_VIP" ; then
-                logger -s "NM dns-vip-prepender-worker: API VIP already the first entry in resolv.conf"
+        if [[ -n $WORKER_BM_IP ]]; then
+            logger -s "NM dns-vip-prepender-worker: Checking if worker node IP is the first entry in resolv.conf"
+            if grep nameserver /etc/resolv.conf | head -n 1 | grep -q "$WORKER_BM_IP" ; then
+                logger -s "NM dns-vip-prepender-worker: worker node IP already the first entry in resolv.conf"
                 exit 0
             else
-                export API_VIP
-    
-                logger -s "NM dns-vip-prepender-worker: Setting dhclient to prepend API VIP in resolv.conf"
+                export WORKER_BM_IP
+
+                logger -s "NM dns-vip-prepender-worker: Setting dhclient to prepend DNS VIP in resolv.conf"
                 envsubst < /etc/dhcp/dhclient.conf.template | tee /etc/dhcp/dhclient.conf
-    
-                logger -s "NM dns-vip-prepender-worker: Looking for 'search $CLUSTER_DOMAIN' in /etc/resolv.conf to place 'nameserver $API_VIP'"
-                sed -i "/^search .*$/a nameserver $API_VIP" /etc/resolv.conf
+
+                logger -s "NM dns-vip-prepender-worker: Looking for 'search $CLUSTER_DOMAIN' in /etc/resolv.conf to place 'nameserver $WORKER_BM_IP'"
+                sed -i "/^search .*$/a nameserver $WORKER_BM_IP" /etc/resolv.conf
             fi
         fi
         ;;
